### ISSUE TITLE
Keys not working?

### ISSUE THREAD

**Issue by skotzko** [dkaslovsky/thread-safe#1] opened 2024-07-25 15:24 UTC
As far as I can tell, I've followed the setup instructions but I'm getting this error when I try to save a thread:

> thread-safe: failed to parse thread: tweet lookup error: twitter callout status 403 Client Forbidden:When authenticating requests to the Twitter API v2 endpoints, you must use keys and tokens from a Twitter developer App that is attached to a Project. You can create a project via the developer portal.

What I tried: 
- have created a Twitter developer account and an app for this
- copied the bearer token from that app
- set `$THREAD_SAFE_TOKEN` in my `.zshrc` file via `export THREAD_SAFE_TOKEN='<bearer token value>'`
- verified the env var is there in my shell by `echo`ing it, it appears correct
- then when I run `thread-safe save "shreyas-not strategy" "https://x.com/shreyas/status/1269331314378813440"` I get the above error

**Comment by dkaslovsky** [comment] 2024-07-25 19:14
Hello, thanks for opening this issue and for using `thread-safe`. This error message is what is returned by the twitter v2 API when the key is associated with an account that does not have sufficient permissions to fetch the tweet. In general this happens when you are on the free tier. As I understand it, after Twitter/X's rolled out their new API pricing model, you must be on a paid plan in order to use this functionality. It's too bad as I run into this myself since I am not a paying twitter subscriber. You could verify this by hitting their API directly (`2/tweets`), but if your account is a free-tier account, this is almost certainly the issue. Please let me know if you have any further questions.

**Comment by skotzko** [comment] 2024-07-25 20:06
Ah, I am indeed on the free tier. Is there any way for this to still work on the free tier?

**Comment by dkaslovsky** [comment] 2024-07-25 21:05
Not to my knowledge, but this is not specific to this repo, but instead that Twitter does not provide access to tweets on the free tier as it used to before their pricing change a few months ago. In other words, even if you went directly against their API to assemble the tweet thread by hand, you wouldn't have access and would receive the same error message as above. This tool should work as intended with an account that has the right access. I'm going to go ahead and close the issue but please feel free to reopen if appropriate. Thanks again!

**Closed as completed by dkaslovsky** 2024-07-25 21:05 UTC
